# Generated by Django 4.1.6 on 2023-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_action_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('RE', 'Рекомендуемые'), ('NE', 'Новинки'), ('SA', 'Распродажа')], default='NE', max_length=2, verbose_name='Тип'),
        ),
    ]
