# Generated by Django 4.1.6 on 2023-12-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_sliders', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Изображения Главная страница',
            },
        ),
    ]
