# Generated by Django 4.1.6 on 2023-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mainpagesliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_sliders', verbose_name='Изображение профиля'),
        ),
    ]
