# Generated by Django 4.1.6 on 2023-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_action_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesliders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_page_sliders', verbose_name='Изображение'),
        ),
    ]
