# Generated by Django 4.1.6 on 2023-12-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_feedbacks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
