# Generated by Django 4.1.6 on 2023-12-29 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_feedbacks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 12, 19, 56, 601666), verbose_name='Дата публикации'),
        ),
    ]
