# Generated by Django 4.1.6 on 2023-12-29 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_feedbacks_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 1, 4, 35, 461641), verbose_name='Дата публикации'),
        ),
    ]
