# Generated by Django 4.1.6 on 2024-01-05 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_feedbacks_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_img', verbose_name='Изображение бренда'),
        ),
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actions_img', verbose_name='Изображение акции'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 15, 49, 50, 37744), verbose_name='Дата публикации'),
        ),
    ]
