# Generated by Django 4.1.6 on 2024-01-07 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_brand_description_brand_image_alter_action_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actions_img', verbose_name='Изображение предложения')),
                ('link', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaranteesText', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание страницы гарантии')),
                ('descriptionSite', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание сайта')),
                ('payText', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание страницы оплаты')),
            ],
            options={
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 19, 46, 21, 64424), verbose_name='Дата публикации'),
        ),
    ]
