# Generated by Django 4.1.6 on 2024-01-07 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_offers_siteinfo_alter_feedbacks_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 19, 50, 33, 203143), verbose_name='Дата публикации'),
        ),
    ]
