# Generated by Django 4.1.6 on 2024-01-07 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_feedbacks_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 20, 6, 2, 75145), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actions_img', verbose_name='Изображение предdddddddложения'),
        ),
    ]
