# Generated by Django 4.1.6 on 2024-01-07 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_feedbacks_date_published_alter_offers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='title',
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 20, 6, 17, 474558), verbose_name='Дата публикации'),
        ),
    ]
