# Generated by Django 5.0 on 2023-12-08 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 17, 37, 3, 7363), verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='Исполнено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 37, 3, 7363), verbose_name='Дата создания корзины'),
        ),
    ]
