# Generated by Django 5.0 on 2023-12-08 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date_delivery_order_executed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 17, 53, 36, 253047), verbose_name='Дата создания корзины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 17, 53, 36, 253047), verbose_name='Дата доставки'),
        ),
    ]
