# Generated by Django 5.0 on 2023-12-12 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cart_options_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed',
            field=models.BooleanField(default=False, verbose_name='Оформлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 14, 14, 7, 228359), verbose_name='Дата создания корзины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 14, 14, 7, 228359), verbose_name='Дата доставки'),
        ),
    ]
