# Generated by Django 5.0 on 2023-12-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
