# Generated by Django 5.0 on 2023-12-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profile_profile_remove_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Профили'},
        ),
    ]
