# Generated by Django 4.1.6 on 2024-01-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_offers_siteinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
